### ISSUE TITLE
Accessibility for subtitles

### ISSUE THREAD

**Issue by tavurth** [deep-entertainment/parrot#1]
Hi, cool plugin!

I noticed from [the screenshot in the asset library](https://raw.githubusercontent.com/deep-entertainment/egoventure-example-game/main/images/screenshots/dialog2.png) that the text can be a little hard to read sometimes.
Perhaps adding a feature with `text-border-width` would help users to make accessible games from the get go?

[This video on the subject](https://www.youtube.com/watch?v=4NGe4dzlukc) is really nice

**Comment by dploeger** [comment]
Thanks a lot! And thanks for noticing that important topic!

The plugin is themeable with the usual Godot theming options. Is that enough to support the required accessibility?

**Comment by tavurth** [comment]
Theme-able is great! Here's [the relevant part](https://youtu.be/4NGe4dzlukc?t=172) from the video.

Basically the rules there would be any of:

- Thick black border around text characters
- A black rectangle around the text as a background

So in the theme case you could probably throw a full-size `ColorRect` in there and give the user the option to choose the color of that (or transparent)

About the black text border, I think that could be achieved by the users font settings (i.e. choosing a font with a black border), however for most indie game devs they wont think about it as a default. It would be cool to have that as a feature.

I'm not really able to test this at the moment, I was just browsing and found a repo which is probably going to be useful to many people over the next few years as Godot explodes in popularity :)

**Comment by dploeger** [comment]
I could provide a default theme that sets a reasonable, a11y friendly design.

**Comment by tavurth** [comment]
Thank you! I think it will pay off :)

**Comment by dploeger** [comment]
I've added a default theme, that should be a11y-friendly, which can be used in one's games and a more detailed documentation about theming in Parrot.

**Comment by dploeger** [comment]
Would that be okay?

**Comment by tavurth** [comment]
Should be perfect! 
I think with that done at least the default is good for A11y, and if developers change it to non a11y then it's their lookout.

Thank you!

**Comment by tavurth** [comment]
Should be perfect! 
I think with that done at least the default is good for A11y, and if developers change it to non a11y then it's their lookout.

Thank you!
