### ISSUE TITLE
Playing a parrot dialog while the game is paused

### ISSUE THREAD

**Issue by ThmsKnz** [deep-entertainment/parrot#2]
I'd like to play a dialog and want to ensure that the player can't do another action while playing it.
Therefore I've set the get_tree().paused to true.
However this is also pausing the ParrotDialog.
To circumvent this, I've set the ParrotDialog 'Pause Mode' to 'Process'.
Could you add an `ignore_pause` parameter like it is available in the Boombox class to change the 'Pause Mode'?

**Comment by dploeger** [comment]
Fascinating. You're asking for the same things that @MikaelNyqvist and I were just talking about. 😂

Already on it.
