### ISSUE TITLE
Subtitles are always enabled

### ISSUE THREAD

**Issue by ThmsKnz** [deep-entertainment/parrot#3]
The variable subtitles is always set to true in parrot_dialog.gd independent of the setting of subtitles in the in-game configuration.

**Comment by dploeger** [comment]
I can reproduce this problem: When disabling subtitles and then restarting the game, although subtitles are disabled in the options, the subtitles are still displayed.

Is that, what you're experiencing here?

**Comment by ThmsKnz** [comment]
Exactly. When disabling subtitles in-game it works fine, when starting the game in disabled subtitles mode, the subtitles are shown.

**Comment by dploeger** [comment]
Then that's an EgoVenture bug. Tracked as deep-entertainment/egoventure#10
